# -*- coding: utf-8 -*-
"""task1_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186pM65xIcqNM7OO0SLDhtxG58lWq2eg7
"""

import requests
import json
import time
import os
from datetime import datetime

# API URLs
TOP_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"

# Required header
headers = {"User-Agent": "TrendPulse/1.0"}

# Keywords for each category
categories = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}

# Function to find category based on title
def get_category(title):
    title = title.lower()
    for cat, words in categories.items():
        for word in words:
            if word in title:
                return cat
    return None


# Step 1: Get top story IDs
try:
    response = requests.get(TOP_URL, headers=headers)
    story_ids = response.json()[:500]
except:
    print("Error fetching top stories")
    exit()

# Store results
results = []
count_per_category = {cat: 0 for cat in categories}

# Step 2: Fetch each story
for story_id in story_ids:

    # Stop when all categories reach 25
    if all(count == 25 for count in count_per_category.values()):
        break

    try:
        res = requests.get(ITEM_URL.format(story_id), headers=headers)
        story = res.json()
    except:
        print(f"Error fetching story {story_id}")
        continue

    if not story or "title" not in story:
        continue

    category = get_category(story["title"])

    if not category:
        continue

    if count_per_category[category] >= 25:
        continue

    # Extract required fields
    data = {
        "post_id": story.get("id"),
        "title": story.get("title"),
        "category": category,
        "score": story.get("score", 0),
        "num_comments": story.get("descendants", 0),
        "author": story.get("by"),
        "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

    results.append(data)
    count_per_category[category] += 1

    # Sleep after completing each category
    if count_per_category[category] == 25:
        print(f"{category} completed. Waiting 2 seconds...")
        time.sleep(2)

# Step 3: Save JSON file
os.makedirs("data", exist_ok=True)

filename = "data/trends_" + datetime.now().strftime("%Y%m%d") + ".json"

with open(filename, "w", encoding="utf-8") as f:
    json.dump(results, f, indent=4)

print(f"Collected {len(results)} stories. Saved to {filename}")

import pandas as pd
import json
import os

folder = "data"

files = [f for f in os.listdir(folder) if f.endswith(".json")]

if len(files) == 0:
    print("No JSON file found. Run Task 1 first.")
    exit()

files.sort()
file_name = files[-1]
file_path = os.path.join(folder, file_name)

print("Reading file:", file_path)

with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.DataFrame(data)

print("\nOriginal shape:", df.shape)

df = df.drop_duplicates(subset=["post_id"])

df["title"] = df["title"].fillna("No Title")

df["author"] = df["author"].fillna("unknown")

df["score"] = df["score"].fillna(0)
df["num_comments"] = df["num_comments"].fillna(0)

df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].astype(int)

df["category"] = df["category"].str.lower()

df = df[df["category"].notna()]

df["engagement"] = df["score"] + df["num_comments"]

print("\nCleaned shape:", df.shape)

csv_file = file_path.replace(".json", ".csv")

df.to_csv(csv_file, index=False)

print("Saved cleaned data to:", csv_file)

import pandas as pd
import numpy as np
import os

folder = "data"

files = [f for f in os.listdir(folder) if f.endswith(".csv")]

if len(files) == 0:
    print("No CSV file found. Run Task 2 first.")
    exit()

files.sort()
file_name = files[-1]
file_path = os.path.join(folder, file_name)

print("Reading file:", file_path)

df = pd.read_csv(file_path)

print("\nData shape:", df.shape)

print("\n--- Basic Statistics ---")
avg_score = np.mean(df["score"])
median_score = np.median(df["score"])
max_score = np.max(df["score"])

avg_comments = np.mean(df["num_comments"])

print("Average Score:", avg_score)
print("Median Score:", median_score)
print("Max Score:", max_score)
print("Average Comments:", avg_comments)

print("\n--- Category Analysis ---")

grouped = df.groupby("category")[["score", "num_comments", "engagement"]].mean()

print(grouped)

print("\n--- Top 5 Posts ---")

top_posts = df.sort_values(by="engagement", ascending=False).head(5)

print(top_posts[["title", "category", "engagement"]])

print("\n--- Top Authors ---")

top_authors = df["author"].value_counts().head(5)

print(top_authors)

print("\n--- Category Count ---")

category_count = df["category"].value_counts()

print(category_count)

summary_file = file_path.replace(".csv", "_summary.txt")

with open(summary_file, "w") as f:
    f.write("Total posts: " + str(len(df)) + "\n")
    f.write("Average score: " + str(avg_score) + "\n")
    f.write("Average comments: " + str(avg_comments) + "\n")
    f.write("Top category: " + category_count.idxmax() + "\n")

print("\nSummary saved to:", summary_file)

import pandas as pd
import matplotlib.pyplot as plt
import os

folder = "data"

files = [f for f in os.listdir(folder) if f.endswith(".csv")]

if len(files) == 0:
    print("No CSV file found. Run Task 2 first.")
    exit()

files.sort()
file_name = files[-1]
file_path = os.path.join(folder, file_name)

print("Reading file:", file_path)

df = pd.read_csv(file_path)

os.makedirs("charts", exist_ok=True)

category_count = df["category"].value_counts()

plt.figure()
category_count.plot(kind="bar")
plt.title("Category Distribution")
plt.xlabel("Category")
plt.ylabel("Number of Posts")

plt.savefig("charts/category_distribution.png")
plt.close()

avg_engagement = df.groupby("category")["engagement"].mean()

plt.figure()
avg_engagement.plot(kind="bar")
plt.title("Average Engagement by Category")
plt.xlabel("Category")
plt.ylabel("Engagement")

plt.savefig("charts/engagement_by_category.png")
plt.close()

plt.figure()
plt.hist(df["score"], bins=20)
plt.title("Score Distribution")
plt.xlabel("Score")
plt.ylabel("Frequency")

plt.savefig("charts/score_distribution.png")
plt.close()

top_posts = df.sort_values(by="engagement", ascending=False).head(5)

plt.figure()
plt.barh(top_posts["title"], top_posts["engagement"])
plt.title("Top 5 High Engagement Posts")
plt.xlabel("Engagement")
plt.ylabel("Title")

plt.savefig("charts/top_posts.png")
plt.close()

print("Charts created and saved in 'charts' folder")