# -*- coding: utf-8 -*-
"""task2_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l6zYcxMjKNy_gz3Z0C4nKr3_6CqCry_3
"""

import pandas as pd
import os


folder = "data"

files = [f for f in os.listdir(folder) if f.endswith(".json")]

if len(files) == 0:
    print("No JSON file found. Run Task 1 first.")
    exit()

files.sort()
file_name = files[-1]
file_path = os.path.join(folder, file_name)

df = pd.read_json(file_path)

print(f"Loaded {len(df)} stories from {file_path}")

df = df.drop_duplicates(subset=["post_id"])
print("After removing duplicates:", len(df))

df = df.dropna(subset=["post_id", "title", "score"])
print("After removing nulls:", len(df))

df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].fillna(0).astype(int)

df = df[df["score"] >= 5]
print("After removing low scores:", len(df))

df["title"] = df["title"].str.strip()

output_path = "data/trends_clean.csv"

df.to_csv(output_path, index=False)

print(f"\nSaved {len(df)} rows to {output_path}")

print("\nStories per category:")
print(df["category"].value_counts())