# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhBARyvAWZJ9m9AC073_Ib02GHrH7j6_
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

# Step 1: Load analysed data
file_path = "data/trends_analysed.csv"

df = pd.read_csv(file_path)

# create outputs folder if not exists
os.makedirs("outputs", exist_ok=True)

# -------------------------------
# Chart 1: Top 10 stories by score
# -------------------------------

top10 = df.sort_values(by="score", ascending=False).head(10)

# shorten long titles
titles = [t[:50] + "..." if len(t) > 50 else t for t in top10["title"]]

plt.figure()
plt.barh(titles, top10["score"])
plt.xlabel("Score")
plt.ylabel("Title")
plt.title("Top 10 Stories by Score")

plt.gca().invert_yaxis()  # highest score on top

plt.savefig("outputs/chart1_top_stories.png")
plt.close()

# -------------------------------
# Chart 2: Stories per category
# -------------------------------

category_counts = df["category"].value_counts()

plt.figure()
plt.bar(category_counts.index, category_counts.values)
plt.xlabel("Category")
plt.ylabel("Number of Stories")
plt.title("Stories per Category")

plt.savefig("outputs/chart2_categories.png")
plt.close()

# -------------------------------
# Chart 3: Score vs Comments
# -------------------------------

popular = df[df["is_popular"] == True]
not_popular = df[df["is_popular"] == False]

plt.figure()
plt.scatter(popular["score"], popular["num_comments"], label="Popular")
plt.scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")

plt.xlabel("Score")
plt.ylabel("Number of Comments")
plt.title("Score vs Comments")
plt.legend()

plt.savefig("outputs/chart3_scatter.png")
plt.close()

# -------------------------------
# Bonus: Dashboard
# -------------------------------

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# Chart 1 in dashboard
axes[0].barh(titles, top10["score"])
axes[0].set_title("Top Stories")
axes[0].invert_yaxis()

# Chart 2 in dashboard
axes[1].bar(category_counts.index, category_counts.values)
axes[1].set_title("Categories")

# Chart 3 in dashboard
axes[2].scatter(popular["score"], popular["num_comments"], label="Popular")
axes[2].scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")
axes[2].set_title("Score vs Comments")
axes[2].legend()

fig.suptitle("TrendPulse Dashboard")

plt.savefig("outputs/dashboard.png")
plt.close()

print("All charts saved in 'outputs' folder")