# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fsP9st4QK90kKF0TWp0gpOaGLrHZbT4u
"""

import pandas as pd
import numpy as np

# Step 1: Load data
file_path = "data/trends_clean.csv"

df = pd.read_csv(file_path)

print(f"Loaded data: {df.shape}")

# show first 5 rows
print("\nFirst 5 rows:")
print(df.head())

# average values
avg_score = df["score"].mean()
avg_comments = df["num_comments"].mean()

print("\nAverage score   :", int(avg_score))
print("Average comments:", int(avg_comments))

# Step 2: NumPy analysis

print("\n--- NumPy Stats ---")

scores = df["score"].values
comments = df["num_comments"].values

print("Mean score   :", int(np.mean(scores)))
print("Median score :", int(np.median(scores)))
print("Std deviation:", int(np.std(scores)))

print("Max score    :", int(np.max(scores)))
print("Min score    :", int(np.min(scores)))

# category with most stories
top_category = df["category"].value_counts().idxmax()
top_count = df["category"].value_counts().max()

print(f"\nMost stories in: {top_category} ({top_count} stories)")

# story with most comments
max_comments_index = np.argmax(comments)
top_story_title = df.iloc[max_comments_index]["title"]
top_story_comments = comments[max_comments_index]

print(f"\nMost commented story: \"{top_story_title}\" — {top_story_comments} comments")

# Step 3: Add new columns

# engagement = comments per score
df["engagement"] = df["num_comments"] / (df["score"] + 1)

# is_popular based on average score
df["is_popular"] = df["score"] > avg_score

# Step 4: Save new file
output_file = "data/trends_analysed.csv"
df.to_csv(output_file, index=False)

print(f"\nSaved to {output_file}")